apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-app
  namespace: dev
spec:
  replicas: 2  # 我们这次试着起 2 个副本！
  selector:
    matchLabels:
      app: journal-api
  template:
    metadata:
      labels:
        app: journal-api
    spec:
      containers:
      - name: journal-container
        # ⚠️ 确保用你之前推送到 Docker Hub 的镜像
        image: rory109/journal-api:latest
        # 策略：Always (总是去拉最新的) 或 IfNotPresent (本地有就用本地的)
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: FULL_DB_URL
        # 存活探针-死机重启
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10 # 刚启动时10s后再开始探测
          periodSeconds: 10 # 每10s探测一次
        # 就绪探针： 没准备好不发流量
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5 # 刚启动时5s后再开始探测
          periodSeconds: 5 # 每5s探测一次
        

---
apiVersion: v1
kind: Service
metadata:
  name: journal-app
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: journal-api
  ports:
  - port: 80
    targetPort: 8000
