# 不在镜像中的CI流程
name: Journal API CI

# 触发条件：push 到 main 分支或发起pull request
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test: 
    # 运行环境-Gituhub上最新的ubuntu虚拟机
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3
      
      # 登录Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # 设置docker buildx
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        users: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/journal-api:latest