# 不在镜像中的CI流程
name: Journal API CI

# 触发条件：push 到 main 分支或发起pull request
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push: 
    # 运行环境-Gituhub上最新的ubuntu虚拟机
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3
      
      # 登录Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # 设置docker buildx
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      # 在context目录下找到dockerfile并在github的虚拟机上进行加载和构建，最后上传到tags处
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/journal-api:latest

    # 部署到Azure
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          envs: DATABASE_URL
          script_stop: true
          # 登录上去后要敲的命令
          script: |
            if [ ! -d "journal-starter" ];then
              git clone https://github.com/Rory109/journal-starter.git
            fi
            cd journal-starter
            # 拉取最新代码
            git pull origin main
            if [ ! -f .env ];then
              echo "DATABASE_URL=$DATABASE_URL" > .env 
            fi
            # 拉取最新镜像
            docker compose pull
            # 用新镜像重启容器
            docker compose up -d
            # 清理旧镜像（节省空间）
            docker image prune -f
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}